# Generated by Django 4.2.6 on 2024-01-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('ipo_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
    ]
