# Generated by Django 4.2.6 on 2024-01-03 16:55
import csv
from django.db import migrations

from stocks.serializers import Stock as StockSerialzier
from stocks.models import Stock as StockModel


def add_stocks(apps, schema_editor):
    file_name = "stocks/migrations/nasdaq_screener.csv"
    with open(file_name) as csvfile:
        stock_reader = csv.reader(csvfile, delimiter=',')
        # Ignore Header
        stock_reader.__next__()
        for stock_line in stock_reader:
            print(stock_line)
            stock = StockSerialzier(data={
                "symbol": stock_line[0],
                "name": stock_line[1],
                "country": stock_line[2],
                "ipo_year": stock_line[3] or 0,
                "sector": stock_line[4],
                "industry": stock_line[5],
            })
            stock.is_valid(raise_exception=True)
            stock.save()


def drop_stocks(apps, schema_editor):
    StockModel.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_stocks,
            reverse_code=drop_stocks,
        ),
    ]
