# Generated by Django 4.2.6 on 2024-01-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20240103_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='tags',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
