# Generated by Django 4.2.6 on 2024-01-03 02:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=255)),
                ('strategy', models.CharField(max_length=255)),
                ('strategy_settings', models.JSONField()),
                ('ml_model', models.CharField(max_length=255)),
                ('ml_model_settings', models.JSONField()),
                ('training_start_date', models.DateField()),
                ('training_end_date', models.DateField()),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision_buy', models.FloatField(blank=True, null=True)),
                ('recall_buy', models.FloatField(blank=True, null=True)),
                ('precision_sell', models.FloatField(blank=True, null=True)),
                ('recall_sell', models.FloatField(blank=True, null=True)),
                ('precision_hold', models.FloatField(blank=True, null=True)),
                ('recall_hold', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Trading Model',
                'verbose_name_plural': 'Trading Models',
            },
        ),
    ]
