# Generated by Django 4.2.6 on 2024-01-06 02:58

from django.db import migrations, models
import trading_models.models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingmodel',
            name='training_end_date',
        ),
        migrations.RemoveField(
            model_name='tradingmodel',
            name='training_start_date',
        ),
        migrations.AddField(
            model_name='tradingmodel',
            name='period',
            field=models.CharField(default=trading_models.models.max_period, max_length=3),
        ),
        migrations.AddField(
            model_name='tradingmodel',
            name='training_percent',
            field=models.FloatField(default=trading_models.models.default_training_percent),
        ),
    ]
