# Generated by Django 4.2.6 on 2024-01-06 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_models', '0002_remove_tradingmodel_training_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingmodel',
            name='ml_model_settings',
        ),
        migrations.RemoveField(
            model_name='tradingmodel',
            name='strategy_settings',
        ),
    ]
