# Generated by Django 4.2.6 on 2024-01-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_models', '0003_remove_tradingmodel_ml_model_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingmodel',
            name='optimal_parameters',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
