# Generated by Django 4.2.6 on 2024-01-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_models', '0005_tradingmodel_model_returns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingmodel',
            name='skip',
            field=models.BooleanField(default=False),
        ),
    ]
